config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :log_entries
  end
end

app/controllers/spree/admin/log_entries_controller.rb
module Spree
  module Admin
    class LogEntriesController < ResourceController
    

    private
      def collection
        return @collection if @collection

        scope = LogEntry.scoped

        scope = scope.where(:source_type => params[:source_type]) if params[:source_type]
        scope = scope.where(:source_id   => params[:source_id])   if params[:source_id]

        @collection = scope.page(params[:page])
      end
    end
  end
end

app/views/spree/admin/log_entries/_active_merchant_response.html.erb
<dl>
  <dt>Authorization Code</dt>
  <dd><%= response.try(:authorization)%></dd>

  <dt>Mode</dt>
  <dd><%= response.try(:test?) ? "Test Mode" : "Production Mode"%></dd>

  <% if response.try(:avs_result) %>
    <dt>Address Verification (AVS)</dt>
    <dd><%= response.avs_result['message'] %></dd>
  <% end %>

  <dt>Status</dt>
  <dd><%= response.try(:success?) ? "Success" : "Failure"%></dd>

  <dt>Mode</dt>
  <dd><%= response.try(:test?) ? "Test Mode" : "Production Mode"%></dd>
</dl>
  <%= link_to "More Info", '#', class: 'more_info', 'data-index' => index %>

  <div id="more_info_<%= index %>" style="display:none">
    <%= render(:partial => 'hash_table', :locals => {:hash => response.avs_result, :title => 'Address Verification (AVS)'}) if response.try(:avs_result) %>
    <%= render(:partial => 'hash_table', :locals => {:hash => response.cvv_result, :title => 'Card Code Verfication (CVV)'}) if response.try(:cvv_result) %>
    <%= render(:partial => 'hash_table', :locals => {:hash => response.params, :title => 'More Details'}) if response.try(:params) %>
  </div>

app/views/spree/admin/log_entries/_hash_table.html.erb
<div class="sixteen columns">
  <h3><%= title %></h3>
  <table class="index">
    <thead>
      <tr>
        <% hash.to_a.sort.each do |key, value| %>
          <% next if key.include?('fee') || key.include?('invoice') || key.include?('livemode') %>
          <th><%= key.humanize.titleize %></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <tr>
        <% hash.to_a.sort.each do |key, value| %>
          <% next if key.include?('fee') || key.include?('invoice') || key.include?('livemode') %>
          <td>
              <% if value.is_a?(Hash) %>
                  <%= debug value %>
              <% else %>
                  <%= value %>
              <% end %>
          </td>
        <% end %>
      </tr>
    </tbody>
  </table>
</div>

app/views/spree/admin/log_entries/index.html.erb
<% content_for :page_title do %>
  Log Entries
<% end %>
<table class="index">
  <thead>
    <tr>
      <th>Source</th>
      <th>Date</th>
      <th width="70%">Details</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @log_entries.each_with_index do |log_entry, index| %>
      <tr>
        <td><%= log_entry.source_type %></td>
        <td><%= log_entry.created_at %></td>
        <td>
          <% if log_entry.details.present? %>
            <% object = YAML.load(log_entry.details) %>
            <% if object.kind_of?(ActiveMerchant::Billing::Response) %>
              <%= render :partial => 'active_merchant_response', :locals => { :response => object, :index => index } %>
            <% else %>
              <% object.inspect %>
            <% end %>
          <% else %>
            unavailable
          <% end %>
        </td>
        <td><%= link_to("View Payment", admin_order_payments_path(log_entry.source.order)) if log_entry.source.kind_of?(Spree::Payment) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @log_entries %>

<script>
  $(".more_info").click(function() {
    var index = $(this).data('index');

    $("#more_info_" + index).dialog({
      draggable: false,
      modal: true,
      position: ["center","center"],
      width: 1020
    })
    return false;
  });
</script>

app/views/spree/admin/payments/_history.html.erb
<td class='align-center'>
  <%= link_to("history", admin_log_entries_path(:source_type => 'Spree::Payment', :source_id => payment.id))%>
  (<%= payment.log_entries.count %>)
</td>